
server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ggomiluv?characterEncoding=utf8
    username: ggomi
    password: ggomi1234!
    driver-class-name: com.mysql.cj.jdbc.Driver


  messages:
    basename: message/message

  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.team.NewLearn.dto.**/*
